# Make a default nginx config for the frontend

# Map User-Agent to determine if the request is loggable
# Set to 0 for health checks (kube-probe and GoogleHC) to avoid log noise, otherwise 1
map $http_user_agent $loggable {
    ~*GoogleHC      0;
    ~*kube-probe    0;
    default         1;
}

server {
    listen 80;
    server_name _;

    # Apply conditional logging
    access_log /var/log/nginx/access.log combined if=$loggable;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}