name: CI - Frontend Service

on:
  push:
    branches:
      - main
    paths:
      - 'todo-fe/**'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'todo-fe/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd todo-fe
          pnpm install

      - name: Run Linter
        run: |
          cd todo-fe
          pnpm run lint

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todo-repo/todo-fe:${{ github.sha }} ./todo-fe
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todo-repo/todo-fe:${{ github.sha }}

      - name: Notify Telegram (success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ✓ CI Build & Test successful

            *Project* : todo-list
            *Service* : todo-fe
            *Branch* : ${{ github.ref_name }}
            *By* : ${{ github.actor }}
            *Commit* : ${{ github.event.head_commit.message }}

      - name: Notify Telegram (failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ✗ CI Build & Test failed

            *Project* : todo-list
            *Service* : todo-fe
            *Branch* : ${{ github.ref_name }}
            *By* : ${{ github.actor }}
            *Commit* : ${{ github.event.pull_request.title || github.event.head_commit.message }}
            *Log* : [View Run Log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
